jobs:
  - name: build-image
    plan:
      - get: master-version
        params:
          bump: patch
      - get: master-branch
      - put: container-image
        params:
          build: master-branch
          tag_file: master-version/version
      - put: master-version
        params:
          file: master-version/version

  - name: deploy
    plan:
      - put: frontend-helm
        params:
          chart: ff-charts/ff-queries-frontend
          version: 0.1.0
          override_values:
            - key: image.tag
              value: master-version

resources:
  - name: master-branch
    type: git
    source:
      uri: git@github.com:netcho/ff-queries-frontend.git
      branch: master
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEoQIBAAKCAQEApOHzHx5dYyDUj5vRzX3mbUCGvRqRFWQIMyKB0lMjkcFcpvyu
        f3UwFQoWANgw3/JLjwqwB7uXAgJStYPpC56YJBq7Le/5ry3BgphEW8JhpHkBasfo
        jwnMpCwwiY80f8cop7kTbWcQCKzBim5ao/ynmWUPj0v40lOcPe6V0VYfV7wo/+r6
        YBzlUNgPxV9W4z2ZH79XyE94As4k9RdUp7BzYzDpJflq58ATg8Ch7OV6X446Zsoj
        W5Rw1Xi1+wQqnEK1tS7+dfLIthwzrFmFmMpWvKdzPlx/MfJxwllu2Mzdf3FLDo9D
        qP7lmxWETLyN6dzNKOfEOYXNlE/OXYxscHR45wIBJQKCAQEAoG0j5u0cl8zqfeO3
        YCd4akyexdSo1orXi7LfLYFTCltFZDQfZ0GWkQLk+ecazA5XWr5KaGN+K3fhxV3A
        JvssPs3mjY+LJvwWOeBCgsr3OD5iPmGkAMtDpqeJK+VH1kU8UCmyCZS1p5NUhrCP
        isxQCt7etO/5A/5S1HlvLIslah1GnBzrEyk9suBU4c9pHll0j4R1/pyUbYlMic6+
        8IDrzITtZgPiXrPWzgVYhMQZ6k91XIZp72Izd9Vfq1BVO6uvTTZzH1LD2LXfKa4u
        NAyhVrvQropCR0teQ20WeRZN6JfuvTtC44WnzxNd7ountccmJSAbAXIzfuZ/EZQO
        BjjyLQKBgQDyBpkkN7VDt/hN6Ycq+oE9/3N068xwJB0CanDiPpJL/owETjivWPEj
        95ljb6G5ZupafknvB3rozGvTpyWV5RTMXfXC5B/OrDZrh4tWxV8Uag1m/PtKJ8PB
        6+KVtYQzWtTIlBE6TTh9j+dseAkkqenxXFBggxwlWKFAwxn+KwgMsQKBgQCuZxer
        qgt3hJWjgfvjbRlN/pH3z7dvUasiGXWDgCfftf/UZ8r2dJYZ4xOHEUFRALXDuy7y
        HhEMBsbqquh2APZYuaTTeL3ppA5p5KJGc0HVZCAgcYv/JHaO9LiCCmOEvKsF/x2S
        1X0Jy6+FgxWnjDuC0Rnyn5fW3M/gVppDabHlFwKBgEFpkSxiFVCSliLlK3NmTHGe
        /JwkDb1xi0zC0mapIJ7q2bv5dxqiaq/GYM7EOYwN+iZLpUeFeyopaUAfVkQwE3WB
        LapLfjfbhFRp0qHUeo/lT7r4Q+qHSaoIZsCtmVn835AoBKf5Mdy/G/PNakFCre40
        oBoVmOd/vOESIrNlk3kNAoGAeo2h7kAju8Tzh6dyu30Ys1jw81OxVSShxO9LqIOR
        pB8GzJv2Z/7mBFpgv8bvoLRkDQATJq1YFknzkCUSDbt8rQzUsEcB/iBBetgDVBmj
        4g8B0Zvl1eJFeTZYJAdM2dCvh6xZ+HpX3V6ysNinbtE+k0bT9pmo99lvewxsZrj5
        jDkCgYBvJ1L6bu5XKl0YzXjcprXd0LS2wycSVYootJzEFWUsBNaKzFCoK13zAJj1
        /lcTIICzzj3liA5psCk/KQh+xiFOkwSGyw9fsvoSCMjiV8u8kAWFPkGrdLdDQPBr
        17jpdIA0DzYl1EknhmNcvRBfZbJPih2w4XhF8bgqZJYfzd574A==
        -----END RSA PRIVATE KEY-----
      git_config:
        - name: core.bigFileThreshold
          value: 10m
  - name: master-version
    type: semver
    source:
      driver: git
      uri: git@github.com:netcho/ff-queries-frontend.git
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEoQIBAAKCAQEApOHzHx5dYyDUj5vRzX3mbUCGvRqRFWQIMyKB0lMjkcFcpvyu
        f3UwFQoWANgw3/JLjwqwB7uXAgJStYPpC56YJBq7Le/5ry3BgphEW8JhpHkBasfo
        jwnMpCwwiY80f8cop7kTbWcQCKzBim5ao/ynmWUPj0v40lOcPe6V0VYfV7wo/+r6
        YBzlUNgPxV9W4z2ZH79XyE94As4k9RdUp7BzYzDpJflq58ATg8Ch7OV6X446Zsoj
        W5Rw1Xi1+wQqnEK1tS7+dfLIthwzrFmFmMpWvKdzPlx/MfJxwllu2Mzdf3FLDo9D
        qP7lmxWETLyN6dzNKOfEOYXNlE/OXYxscHR45wIBJQKCAQEAoG0j5u0cl8zqfeO3
        YCd4akyexdSo1orXi7LfLYFTCltFZDQfZ0GWkQLk+ecazA5XWr5KaGN+K3fhxV3A
        JvssPs3mjY+LJvwWOeBCgsr3OD5iPmGkAMtDpqeJK+VH1kU8UCmyCZS1p5NUhrCP
        isxQCt7etO/5A/5S1HlvLIslah1GnBzrEyk9suBU4c9pHll0j4R1/pyUbYlMic6+
        8IDrzITtZgPiXrPWzgVYhMQZ6k91XIZp72Izd9Vfq1BVO6uvTTZzH1LD2LXfKa4u
        NAyhVrvQropCR0teQ20WeRZN6JfuvTtC44WnzxNd7ountccmJSAbAXIzfuZ/EZQO
        BjjyLQKBgQDyBpkkN7VDt/hN6Ycq+oE9/3N068xwJB0CanDiPpJL/owETjivWPEj
        95ljb6G5ZupafknvB3rozGvTpyWV5RTMXfXC5B/OrDZrh4tWxV8Uag1m/PtKJ8PB
        6+KVtYQzWtTIlBE6TTh9j+dseAkkqenxXFBggxwlWKFAwxn+KwgMsQKBgQCuZxer
        qgt3hJWjgfvjbRlN/pH3z7dvUasiGXWDgCfftf/UZ8r2dJYZ4xOHEUFRALXDuy7y
        HhEMBsbqquh2APZYuaTTeL3ppA5p5KJGc0HVZCAgcYv/JHaO9LiCCmOEvKsF/x2S
        1X0Jy6+FgxWnjDuC0Rnyn5fW3M/gVppDabHlFwKBgEFpkSxiFVCSliLlK3NmTHGe
        /JwkDb1xi0zC0mapIJ7q2bv5dxqiaq/GYM7EOYwN+iZLpUeFeyopaUAfVkQwE3WB
        LapLfjfbhFRp0qHUeo/lT7r4Q+qHSaoIZsCtmVn835AoBKf5Mdy/G/PNakFCre40
        oBoVmOd/vOESIrNlk3kNAoGAeo2h7kAju8Tzh6dyu30Ys1jw81OxVSShxO9LqIOR
        pB8GzJv2Z/7mBFpgv8bvoLRkDQATJq1YFknzkCUSDbt8rQzUsEcB/iBBetgDVBmj
        4g8B0Zvl1eJFeTZYJAdM2dCvh6xZ+HpX3V6ysNinbtE+k0bT9pmo99lvewxsZrj5
        jDkCgYBvJ1L6bu5XKl0YzXjcprXd0LS2wycSVYootJzEFWUsBNaKzFCoK13zAJj1
        /lcTIICzzj3liA5psCk/KQh+xiFOkwSGyw9fsvoSCMjiV8u8kAWFPkGrdLdDQPBr
        17jpdIA0DzYl1EknhmNcvRBfZbJPih2w4XhF8bgqZJYfzd574A==
        -----END RSA PRIVATE KEY-----
        git_config:
        - name: core.bigFileThreshold
          value: 10m
      branch: master
      file: version
  - name: container-image
    type: docker-image
    source:
      repository: netcho/ff-queries-frontend
      username: netcho
      password: 14dc02ca-099c-43e8-a451-5ca3274bee11
  - name: frontend-helm
    type: helm
    source:
      cluster_url: https://10.0.201.172:6443
      cluster_ca: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EWXhNVEV5TVRreU5sb1hEVE13TURZd09URXlNVGt5Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2duCkxiRUJjd0NFZzNvRTBBUTZMcitGblhManFCVDBUNlkyaFBGeUpBNGxua09KVFkvMG9GNkFOUFEzWkhERGNsM2gKTlQrSVFGNVBVQWJuNDBlSWt0Y2FvR3JUS3B3L2pWMTNjN3lQMGR6dE5ZWS8yQVFnbEZwM2N6eVJTa2I3Y1MragpDY0NBL0NmWVZXWUJiZS9BaGlOODcrWDFVeGNPSHNUak1JeUhHR2xCMUJVd2JUQUdrWFkrVG5jSHdLc3lCSno2CjU4WWs1VXIxN2VKVWpHQ3NlZ0JSWFh6ZVhEK1dJeUxjSFhhUFBxQzlyazlHSXNPamlUZElYMGY0OHBvcElKR1oKVFZGdFN6QjJmQkRWQi9pek9FSUJqVmZPekllR2JkSTFIclh3bWJrbnNqYTVNcGU1TC9WU0ZzMXptUW0vcFlmTApPN3NwYklOZ0tLQ1ZqSlViWjZzQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEc2FWMU9DdFBxcmV4b1FsRFhRNWkzOG9uenEKN1FDQUVWSUswZ1BEMGFTY29LaGpaN3JLM0hZQTk4NXQ0bFdXSmh4S2gzTWU0TlpmREJpdXc1NVh2MnRtbWhMZQpxN3JPeXBYSlFzUkhENStuc3lob2U1OFZzM1JmZWdTWU50VmsyMUVNbEV1QTAybEVOUkMvb0l4b2VlRzJtYktPCnhqKy9iVjkyWnIyeStLa0FNT3hRZi9NcExzaEljRCtGcjhoU1U3ZThoNndmdUVVYnNjWE5oMkYrTVJhR0xpRVYKMGpjZ1d4bDM4SitsbVJTc2V6U2NpTWFZQmN1NDR5OVdHcWI5Y0dtZ09QbUhpTzBMLzRZUWltY0lWUko2bjh0NApRZExORVRTbGxnTktRSXNjVUFXbXJZTm8yWnpvTDBuOS9icUpQNU1xU3p5ajZHRVdwL25rYWpxL0ZFOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      admin_key: |
        LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMXV4LzdwY2R3d3VScTN6ZFY4NzgyaU9xdXVZRWZYUXR2SGJJYlROTW1TenlveTkzCnh3SFc0TEQyZFFpNnhjcE1qM08yaFdUZHFzZHg5Zk1Rd2U4SFJBcnRsWjV3NXVKSnV3aXc5WnoyWHpXdlNQaC8KM3R1NG91L21vUzZmZUNubXpnK0daZkVJMzdFSUduR1BxZ3IyWHFVSFdLYk1GWFdMbUlDenFNMUJiNThWcU81RQpOMEFKU2pLQWVEc01zYUltaytpUkpveFZmNFdLeThoRHk3YUg4NEFTQlc1T25EbG9JaVo2eDJrVzBWTWNpNDAyCnl0Z0FCbFRPalRyd3BjZVE4ckxyVDJTNEhCeDlXc082YlliOGMrZkJwSmlKZk5QdXBaK0YyOUt4endzZ1RrMlkKdVZhaWFnVHRzZzFhRHdBMWZ6OVRsa0NJenREMEQ2L3VZanFNY1FJREFRQUJBb0lCQVFDcjU0QXdFdmpBSUFuRQprMXZyTnVqeGhhT3lWL1p4YmJLRFVyTGUvVEFnT0Y1ZWZjSWREL0NSeVpsblpMTVhMc2JyMm82N3hVQ3pyMUVNCmV2MEZVUzJMay80U05TZHkxTDVLZGhvc2FmNTVpdFFIMXBOWWFvQVUrek9KNm1PczFqOEF4RlFvUjVGa2NoSGMKTE1iUEtIT0VvaFR0S0lTR0NYMjlYZnZWWVU4Y2VqZWhjRXdhQkt2UmNwa1lPMFlEUFk4TUM1cHR4U1drN0lsZAo5S2VHNkcvMC9yY0cwVFc3ekZTOWlwZWMvR2xsQ3QrR2JjdWl0a0FjU0ozNks4TUxqclI4RTdoRklUY3RiTWkwCklDd2cwak1kOU1tVGtzK3ZzSWdtVkloZnZTL3ZoSDh5WnRnZVVZRTVQell5Zzd0UkhiYno5UkZLczFMUWhJQSsKRVlKUTFnM1JBb0dCQU9WTFZnYjMySENuQmdwLy9pZ1lFZTJLU1J2K0Zoa3FjODVnMnBLTVB5UDlUaHJKdlEzWgpha2dDZ1pUb1BYTEphdTNrTHlCek4xQi9rVXNxSGpidzRPRTRkY3J4NjQ2VzdObTl2NlBTZUxaeVF0L09xZ1RvCm1Lbm9DT1RWeVpFUlhUeGlxU0RXcGloMzRNRC9yaHF6Z3JweW81K0plWVN2NkpxVU8vUXZLYU9GQW9HQkFPLzAKc1U5Rm4yMkRkaXhSclRaclZndms5U1BxVzR0SmdqVHZsSU5na1lUaGV1SnlDRTY4OThQbEkrN0IzM1VvMkt4egp3bmVRcFU1NE02Z3RZenNQY1JUTUdQbXpqNnkycWM0TWFOTGIwblo0eExPeFJjZHVEZXRGZXNkUGh6RnVHTXFrCmowUDRnSDI0NGVQNE8rM2d5QkhJT3lmZVhBYWJlYXA4WGhUcjZjcjlBb0dCQUlETU1aV1djTWpPdVZENmxueFYKRVBUNmdaaXN3Q01BdXE1SnIxMDBWRjlWOFNLUkFaWWU4MWxodHdJNjloRmRYS2dtVGVhUGNablJIbjgzT0dPcQpLTmU2REVpa1hhbnAwejk0RzRiZE9odFowWURBS0xhN0pNNEQzY01VNTdXS0tISThCVDdCOC9HMWJOVmNpYUxNCkJQblFYV0xIS1RCRVU0ZEpEdWhaK2F5MUFvR0FJeUoxQStKeDRac3FKbnNmSGFUQnlLUVJzTnlUNHVVMGg0TzgKL3krWW54aFU0ZXRJaEI3dk9HUEl5eURnRTB1VHpreDA0UVR3NzNoeU4rSE5jY3hsQm1LTUZhUFJHYnoxU0JKUgpGdTdROWovZ3JWNzdsS1BzcmRKU2svUjFHeXUvdll3eTNnVDQ2Mit5dzZxSk85OTU3QUNoaU1qcU9KMXpSeDlHCnQxR0R2aEVDZ1lCSExEcW9WVjU1OEErMGQ3MUtIdDZ2MTVFM0dsUHFZRkxKTkpKbWYvUjlDRERYNENPR1BZeE4KaU52bW5Qd0N1VU14VzBGUE1HZkp2cW1RUENveXVwQXRuV2E1ZHk5dGRjTjlWVWVhUDRpRHhVaXNubXBaT0RqVApXVlZqM3ZlS3I4MnNUTmVjUDRkSHViUGtoNEhOenl4VVRUbW1mcC9XeTRBMGVqYnBHSGd5UUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
      admin_cert: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwakNDQWJxZ0F3SUJBZ0lJREZyQ2I2eEp4UWN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TURBMk1URXhNakU1TWpaYUZ3MHlNVEEyTVRJeE1ESTBNelphTUJReApFakFRQmdOVkJBTVRDV052Ym1OdmRYSnpaVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DCmdnRUJBTmJzZis2WEhjTUxrYXQ4M1ZmTy9Ob2pxcnJtQkgxMExieDJ5RzB6VEprczhxTXZkOGNCMXVDdzluVUkKdXNYS1RJOXp0b1ZrM2FySGNmWHpFTUh2QjBRSzdaV2VjT2JpU2JzSXNQV2M5bDgxcjBqNGY5N2J1S0x2NXFFdQpuM2dwNXM0UGhtWHhDTit4Q0JweGo2b0s5bDZsQjFpbXpCVjFpNWlBczZqTlFXK2ZGYWp1UkRkQUNVb3lnSGc3CkRMR2lKcFBva1NhTVZYK0Zpc3ZJUTh1MmgvT0FFZ1Z1VHB3NWFDSW1lc2RwRnRGVEhJdU5Oc3JZQUFaVXpvMDYKOEtYSGtQS3k2MDlrdUJ3Y2ZWckR1bTJHL0hQbndhU1lpWHpUN3FXZmhkdlNzYzhMSUU1Tm1MbFdvbW9FN2JJTgpXZzhBTlg4L1U1WkFpTTdROUErdjdtSTZqSEVDQXdFQUFhTW5NQ1V3RGdZRFZSMFBBUUgvQkFRREFnV2dNQk1HCkExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQThxZ0h4ODhZR0VTNzAKUFpnRFlvUTBIQ054Wk9uUVpXbFJBd29pWEgxWGxoVFpCL2ttdFU2MEVDUEZKOWY3U1FIY0xScXRxZGt6YjBPeApKMkhscFFnb1VaNHI2cEIzbjBiMU8xZzhsQ3hvU2tVUXpjYmxac1BBeFMvZVNPaFBPRE5UbmordExRSll1SEovCjIwTXZuZFFCUFd0UkZRRS8yTE5wN1pESTBFK3NiWTlRcE1ydTlIV2JDbjZ3bFlzSExzRklhYVZsZFFRU0YvckUKQmRxWkFVaFNMb09Zd2IyUWVYOEgxSHBuaGhlalZLanVXM3FYNnlXYkcwV1AxODBuYk9JdEhtVGJsQmNSR3FNMAprM2FFalkzWHZkejNMemhpUGd2Z2NCZ3ZBYUtpbXhpVVE3WFBZSFJabE82NnlSR1JLMjF0eDJUTDdGWFFGbEFrCllkc0Y1Z1Y1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      repos:
        - name: ff-charts
          url: http://10.0.201.172:8000

resource_types:
  - name: helm
    type: docker-image
    source:
      repository: linkyard/concourse-helm-resource