jobs:
  - name: build-image
    plan:
      - get: master-version
        params:
          bump: patch
      - get: master-branch
        trigger: true
      - put: container-image
        params:
          build: master-branch
          tag_file: master-version/version
      - put: master-version
        params:
          file: master-version/version

  - name: deploy
    plan:
      - get: master-version
      - put: frontend-helm
        params:
          chart: ff-charts/ff-queries-frontend
          version: 0.1.2
          release: ff-queries-frontend
          override_values:
            - key: image.tag
              value: master-version/version

resources:
  - name: master-branch
    type: git
    source:
      uri: git@github.com:netcho/ff-queries-frontend.git
      branch: master
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEoQIBAAKCAQEApOHzHx5dYyDUj5vRzX3mbUCGvRqRFWQIMyKB0lMjkcFcpvyu
        f3UwFQoWANgw3/JLjwqwB7uXAgJStYPpC56YJBq7Le/5ry3BgphEW8JhpHkBasfo
        jwnMpCwwiY80f8cop7kTbWcQCKzBim5ao/ynmWUPj0v40lOcPe6V0VYfV7wo/+r6
        YBzlUNgPxV9W4z2ZH79XyE94As4k9RdUp7BzYzDpJflq58ATg8Ch7OV6X446Zsoj
        W5Rw1Xi1+wQqnEK1tS7+dfLIthwzrFmFmMpWvKdzPlx/MfJxwllu2Mzdf3FLDo9D
        qP7lmxWETLyN6dzNKOfEOYXNlE/OXYxscHR45wIBJQKCAQEAoG0j5u0cl8zqfeO3
        YCd4akyexdSo1orXi7LfLYFTCltFZDQfZ0GWkQLk+ecazA5XWr5KaGN+K3fhxV3A
        JvssPs3mjY+LJvwWOeBCgsr3OD5iPmGkAMtDpqeJK+VH1kU8UCmyCZS1p5NUhrCP
        isxQCt7etO/5A/5S1HlvLIslah1GnBzrEyk9suBU4c9pHll0j4R1/pyUbYlMic6+
        8IDrzITtZgPiXrPWzgVYhMQZ6k91XIZp72Izd9Vfq1BVO6uvTTZzH1LD2LXfKa4u
        NAyhVrvQropCR0teQ20WeRZN6JfuvTtC44WnzxNd7ountccmJSAbAXIzfuZ/EZQO
        BjjyLQKBgQDyBpkkN7VDt/hN6Ycq+oE9/3N068xwJB0CanDiPpJL/owETjivWPEj
        95ljb6G5ZupafknvB3rozGvTpyWV5RTMXfXC5B/OrDZrh4tWxV8Uag1m/PtKJ8PB
        6+KVtYQzWtTIlBE6TTh9j+dseAkkqenxXFBggxwlWKFAwxn+KwgMsQKBgQCuZxer
        qgt3hJWjgfvjbRlN/pH3z7dvUasiGXWDgCfftf/UZ8r2dJYZ4xOHEUFRALXDuy7y
        HhEMBsbqquh2APZYuaTTeL3ppA5p5KJGc0HVZCAgcYv/JHaO9LiCCmOEvKsF/x2S
        1X0Jy6+FgxWnjDuC0Rnyn5fW3M/gVppDabHlFwKBgEFpkSxiFVCSliLlK3NmTHGe
        /JwkDb1xi0zC0mapIJ7q2bv5dxqiaq/GYM7EOYwN+iZLpUeFeyopaUAfVkQwE3WB
        LapLfjfbhFRp0qHUeo/lT7r4Q+qHSaoIZsCtmVn835AoBKf5Mdy/G/PNakFCre40
        oBoVmOd/vOESIrNlk3kNAoGAeo2h7kAju8Tzh6dyu30Ys1jw81OxVSShxO9LqIOR
        pB8GzJv2Z/7mBFpgv8bvoLRkDQATJq1YFknzkCUSDbt8rQzUsEcB/iBBetgDVBmj
        4g8B0Zvl1eJFeTZYJAdM2dCvh6xZ+HpX3V6ysNinbtE+k0bT9pmo99lvewxsZrj5
        jDkCgYBvJ1L6bu5XKl0YzXjcprXd0LS2wycSVYootJzEFWUsBNaKzFCoK13zAJj1
        /lcTIICzzj3liA5psCk/KQh+xiFOkwSGyw9fsvoSCMjiV8u8kAWFPkGrdLdDQPBr
        17jpdIA0DzYl1EknhmNcvRBfZbJPih2w4XhF8bgqZJYfzd574A==
        -----END RSA PRIVATE KEY-----
      git_config:
        - name: core.bigFileThreshold
          value: 10m
  - name: master-version
    type: semver
    source:
      driver: git
      uri: git@github.com:netcho/ff-queries-frontend.git
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEoQIBAAKCAQEApOHzHx5dYyDUj5vRzX3mbUCGvRqRFWQIMyKB0lMjkcFcpvyu
        f3UwFQoWANgw3/JLjwqwB7uXAgJStYPpC56YJBq7Le/5ry3BgphEW8JhpHkBasfo
        jwnMpCwwiY80f8cop7kTbWcQCKzBim5ao/ynmWUPj0v40lOcPe6V0VYfV7wo/+r6
        YBzlUNgPxV9W4z2ZH79XyE94As4k9RdUp7BzYzDpJflq58ATg8Ch7OV6X446Zsoj
        W5Rw1Xi1+wQqnEK1tS7+dfLIthwzrFmFmMpWvKdzPlx/MfJxwllu2Mzdf3FLDo9D
        qP7lmxWETLyN6dzNKOfEOYXNlE/OXYxscHR45wIBJQKCAQEAoG0j5u0cl8zqfeO3
        YCd4akyexdSo1orXi7LfLYFTCltFZDQfZ0GWkQLk+ecazA5XWr5KaGN+K3fhxV3A
        JvssPs3mjY+LJvwWOeBCgsr3OD5iPmGkAMtDpqeJK+VH1kU8UCmyCZS1p5NUhrCP
        isxQCt7etO/5A/5S1HlvLIslah1GnBzrEyk9suBU4c9pHll0j4R1/pyUbYlMic6+
        8IDrzITtZgPiXrPWzgVYhMQZ6k91XIZp72Izd9Vfq1BVO6uvTTZzH1LD2LXfKa4u
        NAyhVrvQropCR0teQ20WeRZN6JfuvTtC44WnzxNd7ountccmJSAbAXIzfuZ/EZQO
        BjjyLQKBgQDyBpkkN7VDt/hN6Ycq+oE9/3N068xwJB0CanDiPpJL/owETjivWPEj
        95ljb6G5ZupafknvB3rozGvTpyWV5RTMXfXC5B/OrDZrh4tWxV8Uag1m/PtKJ8PB
        6+KVtYQzWtTIlBE6TTh9j+dseAkkqenxXFBggxwlWKFAwxn+KwgMsQKBgQCuZxer
        qgt3hJWjgfvjbRlN/pH3z7dvUasiGXWDgCfftf/UZ8r2dJYZ4xOHEUFRALXDuy7y
        HhEMBsbqquh2APZYuaTTeL3ppA5p5KJGc0HVZCAgcYv/JHaO9LiCCmOEvKsF/x2S
        1X0Jy6+FgxWnjDuC0Rnyn5fW3M/gVppDabHlFwKBgEFpkSxiFVCSliLlK3NmTHGe
        /JwkDb1xi0zC0mapIJ7q2bv5dxqiaq/GYM7EOYwN+iZLpUeFeyopaUAfVkQwE3WB
        LapLfjfbhFRp0qHUeo/lT7r4Q+qHSaoIZsCtmVn835AoBKf5Mdy/G/PNakFCre40
        oBoVmOd/vOESIrNlk3kNAoGAeo2h7kAju8Tzh6dyu30Ys1jw81OxVSShxO9LqIOR
        pB8GzJv2Z/7mBFpgv8bvoLRkDQATJq1YFknzkCUSDbt8rQzUsEcB/iBBetgDVBmj
        4g8B0Zvl1eJFeTZYJAdM2dCvh6xZ+HpX3V6ysNinbtE+k0bT9pmo99lvewxsZrj5
        jDkCgYBvJ1L6bu5XKl0YzXjcprXd0LS2wycSVYootJzEFWUsBNaKzFCoK13zAJj1
        /lcTIICzzj3liA5psCk/KQh+xiFOkwSGyw9fsvoSCMjiV8u8kAWFPkGrdLdDQPBr
        17jpdIA0DzYl1EknhmNcvRBfZbJPih2w4XhF8bgqZJYfzd574A==
        -----END RSA PRIVATE KEY-----
        git_config:
        - name: core.bigFileThreshold
          value: 10m
      branch: master
      file: version
  - name: container-image
    type: docker-image
    source:
      repository: netcho/ff-queries-frontend
      username: netcho
      password: 14dc02ca-099c-43e8-a451-5ca3274bee11
  - name: frontend-helm
    type: helm
    source:
      cluster_url: https://10.0.201.172:6443
      cluster_ca: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EWXhNVEV5TVRreU5sb1hEVE13TURZd09URXlNVGt5Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2duCkxiRUJjd0NFZzNvRTBBUTZMcitGblhManFCVDBUNlkyaFBGeUpBNGxua09KVFkvMG9GNkFOUFEzWkhERGNsM2gKTlQrSVFGNVBVQWJuNDBlSWt0Y2FvR3JUS3B3L2pWMTNjN3lQMGR6dE5ZWS8yQVFnbEZwM2N6eVJTa2I3Y1MragpDY0NBL0NmWVZXWUJiZS9BaGlOODcrWDFVeGNPSHNUak1JeUhHR2xCMUJVd2JUQUdrWFkrVG5jSHdLc3lCSno2CjU4WWs1VXIxN2VKVWpHQ3NlZ0JSWFh6ZVhEK1dJeUxjSFhhUFBxQzlyazlHSXNPamlUZElYMGY0OHBvcElKR1oKVFZGdFN6QjJmQkRWQi9pek9FSUJqVmZPekllR2JkSTFIclh3bWJrbnNqYTVNcGU1TC9WU0ZzMXptUW0vcFlmTApPN3NwYklOZ0tLQ1ZqSlViWjZzQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEc2FWMU9DdFBxcmV4b1FsRFhRNWkzOG9uenEKN1FDQUVWSUswZ1BEMGFTY29LaGpaN3JLM0hZQTk4NXQ0bFdXSmh4S2gzTWU0TlpmREJpdXc1NVh2MnRtbWhMZQpxN3JPeXBYSlFzUkhENStuc3lob2U1OFZzM1JmZWdTWU50VmsyMUVNbEV1QTAybEVOUkMvb0l4b2VlRzJtYktPCnhqKy9iVjkyWnIyeStLa0FNT3hRZi9NcExzaEljRCtGcjhoU1U3ZThoNndmdUVVYnNjWE5oMkYrTVJhR0xpRVYKMGpjZ1d4bDM4SitsbVJTc2V6U2NpTWFZQmN1NDR5OVdHcWI5Y0dtZ09QbUhpTzBMLzRZUWltY0lWUko2bjh0NApRZExORVRTbGxnTktRSXNjVUFXbXJZTm8yWnpvTDBuOS9icUpQNU1xU3p5ajZHRVdwL25rYWpxL0ZFOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      token: |
        eyJhbGciOiJSUzI1NiIsImtpZCI6InNESm1rQnA1QUdBMGtFbjdzMkVQd0pBUVA4U1RTTW93NnlUSDJkeEtCTkkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImNvbmNvdXJzZS10b2tlbi1ubjliMiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjb25jb3Vyc2UiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJkYjJjYjQzNS1iYTdjLTRlOTItODZjMS1jNjFkNjFhODk3MTIiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpjb25jb3Vyc2UifQ.oixTwrv5wfRUnx402ck-l9VxVbgGrWafp6Fvn5PeyGSd9gZ1TkHsqeMqe2wqcBVRSVbIOZwrhgqAgQEBC2_mx62IvRTBhBzzlbXWU4iMD-3EUNWzUlCv3cz7MlCN497Hj2tZZRW-37m1RyjHJYRe3Ud4fV1uCGlmMmCpmwm9l-f4UcMAPQpd9exbH9CzXNdQ7-P_kbsaagN7Jayy0yZkYs7Y_nBBLCtPS7Cn_seBtpr5z1h7PsDmRT-27RJAD3bwODN8dZeenXZ5-Lg5AwZb9xDT8u9w2uKpey7YpYfKj2TU-jyu6JU98OrXJt_xQLlHCBKxKjl_WwXj-gT-jEoj5Q
      repos:
        - name: ff-charts
          url: http://10.0.201.172:8000

resource_types:
  - name: helm
    type: docker-image
    source:
      repository: typositoire/concourse-helm3-resource