jobs:
  - name: build-image
    plan:
      - get: master-version
        params:
          bump: patch
      - get: master-branch
        trigger: true
      - put: container-image
        params:
          build: master-branch
          tag_file: master-version/version
      - put: master-version

resources:
  - name: master-branch
    type: git
    source:
      uri: git@github.com:netcho/ff-queries-frontend.git
      branch: master
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEoQIBAAKCAQEApOHzHx5dYyDUj5vRzX3mbUCGvRqRFWQIMyKB0lMjkcFcpvyu
        f3UwFQoWANgw3/JLjwqwB7uXAgJStYPpC56YJBq7Le/5ry3BgphEW8JhpHkBasfo
        jwnMpCwwiY80f8cop7kTbWcQCKzBim5ao/ynmWUPj0v40lOcPe6V0VYfV7wo/+r6
        YBzlUNgPxV9W4z2ZH79XyE94As4k9RdUp7BzYzDpJflq58ATg8Ch7OV6X446Zsoj
        W5Rw1Xi1+wQqnEK1tS7+dfLIthwzrFmFmMpWvKdzPlx/MfJxwllu2Mzdf3FLDo9D
        qP7lmxWETLyN6dzNKOfEOYXNlE/OXYxscHR45wIBJQKCAQEAoG0j5u0cl8zqfeO3
        YCd4akyexdSo1orXi7LfLYFTCltFZDQfZ0GWkQLk+ecazA5XWr5KaGN+K3fhxV3A
        JvssPs3mjY+LJvwWOeBCgsr3OD5iPmGkAMtDpqeJK+VH1kU8UCmyCZS1p5NUhrCP
        isxQCt7etO/5A/5S1HlvLIslah1GnBzrEyk9suBU4c9pHll0j4R1/pyUbYlMic6+
        8IDrzITtZgPiXrPWzgVYhMQZ6k91XIZp72Izd9Vfq1BVO6uvTTZzH1LD2LXfKa4u
        NAyhVrvQropCR0teQ20WeRZN6JfuvTtC44WnzxNd7ountccmJSAbAXIzfuZ/EZQO
        BjjyLQKBgQDyBpkkN7VDt/hN6Ycq+oE9/3N068xwJB0CanDiPpJL/owETjivWPEj
        95ljb6G5ZupafknvB3rozGvTpyWV5RTMXfXC5B/OrDZrh4tWxV8Uag1m/PtKJ8PB
        6+KVtYQzWtTIlBE6TTh9j+dseAkkqenxXFBggxwlWKFAwxn+KwgMsQKBgQCuZxer
        qgt3hJWjgfvjbRlN/pH3z7dvUasiGXWDgCfftf/UZ8r2dJYZ4xOHEUFRALXDuy7y
        HhEMBsbqquh2APZYuaTTeL3ppA5p5KJGc0HVZCAgcYv/JHaO9LiCCmOEvKsF/x2S
        1X0Jy6+FgxWnjDuC0Rnyn5fW3M/gVppDabHlFwKBgEFpkSxiFVCSliLlK3NmTHGe
        /JwkDb1xi0zC0mapIJ7q2bv5dxqiaq/GYM7EOYwN+iZLpUeFeyopaUAfVkQwE3WB
        LapLfjfbhFRp0qHUeo/lT7r4Q+qHSaoIZsCtmVn835AoBKf5Mdy/G/PNakFCre40
        oBoVmOd/vOESIrNlk3kNAoGAeo2h7kAju8Tzh6dyu30Ys1jw81OxVSShxO9LqIOR
        pB8GzJv2Z/7mBFpgv8bvoLRkDQATJq1YFknzkCUSDbt8rQzUsEcB/iBBetgDVBmj
        4g8B0Zvl1eJFeTZYJAdM2dCvh6xZ+HpX3V6ysNinbtE+k0bT9pmo99lvewxsZrj5
        jDkCgYBvJ1L6bu5XKl0YzXjcprXd0LS2wycSVYootJzEFWUsBNaKzFCoK13zAJj1
        /lcTIICzzj3liA5psCk/KQh+xiFOkwSGyw9fsvoSCMjiV8u8kAWFPkGrdLdDQPBr
        17jpdIA0DzYl1EknhmNcvRBfZbJPih2w4XhF8bgqZJYfzd574A==
        -----END RSA PRIVATE KEY-----
      git_config:
        - name: core.bigFileThreshold
          value: 10m
  - name: master-version
    type: semver
    source:
      driver: git
      uri: git@github.com:netcho/ff-queries-frontend.git
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEoQIBAAKCAQEApOHzHx5dYyDUj5vRzX3mbUCGvRqRFWQIMyKB0lMjkcFcpvyu
        f3UwFQoWANgw3/JLjwqwB7uXAgJStYPpC56YJBq7Le/5ry3BgphEW8JhpHkBasfo
        jwnMpCwwiY80f8cop7kTbWcQCKzBim5ao/ynmWUPj0v40lOcPe6V0VYfV7wo/+r6
        YBzlUNgPxV9W4z2ZH79XyE94As4k9RdUp7BzYzDpJflq58ATg8Ch7OV6X446Zsoj
        W5Rw1Xi1+wQqnEK1tS7+dfLIthwzrFmFmMpWvKdzPlx/MfJxwllu2Mzdf3FLDo9D
        qP7lmxWETLyN6dzNKOfEOYXNlE/OXYxscHR45wIBJQKCAQEAoG0j5u0cl8zqfeO3
        YCd4akyexdSo1orXi7LfLYFTCltFZDQfZ0GWkQLk+ecazA5XWr5KaGN+K3fhxV3A
        JvssPs3mjY+LJvwWOeBCgsr3OD5iPmGkAMtDpqeJK+VH1kU8UCmyCZS1p5NUhrCP
        isxQCt7etO/5A/5S1HlvLIslah1GnBzrEyk9suBU4c9pHll0j4R1/pyUbYlMic6+
        8IDrzITtZgPiXrPWzgVYhMQZ6k91XIZp72Izd9Vfq1BVO6uvTTZzH1LD2LXfKa4u
        NAyhVrvQropCR0teQ20WeRZN6JfuvTtC44WnzxNd7ountccmJSAbAXIzfuZ/EZQO
        BjjyLQKBgQDyBpkkN7VDt/hN6Ycq+oE9/3N068xwJB0CanDiPpJL/owETjivWPEj
        95ljb6G5ZupafknvB3rozGvTpyWV5RTMXfXC5B/OrDZrh4tWxV8Uag1m/PtKJ8PB
        6+KVtYQzWtTIlBE6TTh9j+dseAkkqenxXFBggxwlWKFAwxn+KwgMsQKBgQCuZxer
        qgt3hJWjgfvjbRlN/pH3z7dvUasiGXWDgCfftf/UZ8r2dJYZ4xOHEUFRALXDuy7y
        HhEMBsbqquh2APZYuaTTeL3ppA5p5KJGc0HVZCAgcYv/JHaO9LiCCmOEvKsF/x2S
        1X0Jy6+FgxWnjDuC0Rnyn5fW3M/gVppDabHlFwKBgEFpkSxiFVCSliLlK3NmTHGe
        /JwkDb1xi0zC0mapIJ7q2bv5dxqiaq/GYM7EOYwN+iZLpUeFeyopaUAfVkQwE3WB
        LapLfjfbhFRp0qHUeo/lT7r4Q+qHSaoIZsCtmVn835AoBKf5Mdy/G/PNakFCre40
        oBoVmOd/vOESIrNlk3kNAoGAeo2h7kAju8Tzh6dyu30Ys1jw81OxVSShxO9LqIOR
        pB8GzJv2Z/7mBFpgv8bvoLRkDQATJq1YFknzkCUSDbt8rQzUsEcB/iBBetgDVBmj
        4g8B0Zvl1eJFeTZYJAdM2dCvh6xZ+HpX3V6ysNinbtE+k0bT9pmo99lvewxsZrj5
        jDkCgYBvJ1L6bu5XKl0YzXjcprXd0LS2wycSVYootJzEFWUsBNaKzFCoK13zAJj1
        /lcTIICzzj3liA5psCk/KQh+xiFOkwSGyw9fsvoSCMjiV8u8kAWFPkGrdLdDQPBr
        17jpdIA0DzYl1EknhmNcvRBfZbJPih2w4XhF8bgqZJYfzd574A==
        -----END RSA PRIVATE KEY-----
        git_config:
        - name: core.bigFileThreshold
          value: 10m
      branch: master
      file: version
  - name: container-image
    type: docker-image
    source:
      repository: netcho/ff-queries-frontend
      username: netcho
      password: 14dc02ca-099c-43e8-a451-5ca3274bee11